package org.dromara.system.oss.migration;

public enum OssMigrationError {
    INVALID_REQUEST,
    BATCH_NOT_FOUND,
    OBJECT_NOT_FOUND,
    STORAGE_NOT_SERVING,
    ACCESS_POLICY_MISMATCH,
    TARGET_CONFLICT,
    COPY_FAILED,
    CONTENT_MISMATCH,
    SERVICE_DRIFT,
    ACCESS_VERIFICATION_FAILED,
    CLEANUP_NOT_APPROVED,
    CLEANUP_WINDOW_OPEN,
    INVALID_STATE,
    CLEANUP_FAILED
}
